#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

#=================================================
#	System Required: Debian/Ubuntu
#	Description:3proxy
#	Version: 1.0
#	Author:
#=================================================

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

#Check OS
if [[ -f /etc/redhat-release ]]; then
		release="centos"
	elif cat /etc/issue | grep -q -E -i "debian"; then
		release="debian"
	elif cat /etc/issue | grep -q -E -i "ubuntu"; then
		release="ubuntu"
	elif cat /etc/issue | grep -q -E -i "centos|red hat|redhat"; then
		release="centos"
	elif cat /proc/version | grep -q -E -i "debian"; then
		release="debian"
	elif cat /proc/version | grep -q -E -i "ubuntu"; then
		release="ubuntu"
	elif cat /proc/version | grep -q -E -i "centos|red hat|redhat"; then
		release="centos"
fi

if [ ${release} == "centos" ];then
	ehco "Error: You must be ubuntu to run this script"
fi


bit=`uname -m`
dir=`pwd`

install(){
	#Install 
	apt-get update
	apt-get install make gcc+ -y
	apt-get install wget 
	mkdir -p /var/log/3proxy/

	#Download 3proxy 

	wget -O 3proxy.tar.gz https://github.com/z3APA3A/3proxy/archive/0.8.11.tar.gz
	tar   zxvf  $dir/3proxy.tar.gz  -C  /usr/local/
	ln -s /usr/local/3proxy-0.8.11  /usr/local/3proxy
	cd /usr/local/3proxy 
	make -f Makefile.Linux
	make -f Makefile.Linux install
}


setup(){
	#3proxy  config
cat > /etc/3proxy.cfg<<EOF
daemon
#Authentication
#CL = Clear Text, CR = Encrypted Passswords (MD5)
#Add MD5 users with MD5 passwords with "" (see below)
#users "user:CR:$1$lFDGlder$pLRb4cU2D7GAT58YQvY49."
users xxjaoeid:CL:keij*j3jdh
#Logging
log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30
#Auth type
auth strong
#Binding address
#external /etc/network/interfaces
#external $./external.ip
external 0.0.0.0
internal 0.0.0.0
#internal 45.114.168.157
#SOCKS5
auth strong
flush
allow xxjaoeid
maxconn 384
EOF

    #IP addr 
	IP=$(ip addr | awk '/inet/{print $2}'| awk -F "\/" '{print $1}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\."  )
	for i in $IP
	do
	echo "socks -i$i -e$i -p1080"  >> /etc/3proxy.cfg
	done

	#service
	if [ -f /usr/local/bin/3proxy ];then
		wget --no-check-certificate https://raw.githubusercontent.com/Freesheep/myscript/master/3proxy -O /etc/init.d/3proxy
		chmod +x  /etc/init.d/3proxy
        update-rc.d -f 3proxy defaults
        /etc/init.d/3proxy start
    fi

}

#install 3proxy

install_3proxy(){
	install
	setup

}



# Initialization step
action=$1
[ -z $1 ] && action=install
case "$action" in
    install|uninstall)
        ${action}_3proxy
        ;;
    *)
        echo "Arguments error! [${action}]"
        echo "Usage: `basename $0` [install|uninstall]"
        ;;
esac
	
